name: LaTeX PDF
on:
  push:
    paths: ["**.tex", "**.bib", "**.sty", "**.cls", "figures/**"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: main.pdf
